
Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-22.04"
  config.vm.synced_folder "./", "/home/vagrant/deploy"

  config.vm.define "maddouS" do |maddouS|
    maddouS.vm.hostname = "maddouS"
    maddouS.vm.network "private_network", ip: "192.168.56.110"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
      vb.name = "maddouS"
    end
    config.vm.provision "shell", path: "scripts/install_k3s.sh"
    config.vm.provision "shell", path: "scripts/deploy.sh"
  end

end
